# Docker Compose file for running the agent-ui-service with mock repository
# @author Rishijeet

version: '3.8'

services:
  agent-ui:
    build:
      context: ./agent-ui-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Explicitly disable database auto-configuration
      SPRING_AUTOCONFIGURE_EXCLUDE: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/dashboard"]
      interval: 30s
      timeout: 10s
      retries: 3 